name: mobx_calculator_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.6
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  math_expressions: ^2.5.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.11
  

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


